### ISSUE TITLE
Hockey schedule displaying incorrect date

### ISSUE THREAD

**Issue by eclampett** [JPBetley/pulse#66] opened 2015-09-03 01:18 UTC
The current hockey page displays the wrong date for the next game. This is likely due to how we handle and sort the data when bringing it in from RIT's website.

**Comment by vladionescu** [comment] 2015-10-29 00:35
Resolved by PR #76 

The issue is in HockeyController the $games were being sort()'ed instead of sortBy()'ed.

The Collection::sort() method assumes the collection is single dimensional and attempts to sort based on those values.

Collection::sortBy() takes a callback and functions as we have been attempting to use sort().

Why did Laravel not throw any error regarding sort() being improperly used? It just silently failed...sad.

**Closed as completed by vladionescu** 2015-10-29 00:35 UTC
